person:
  boss: true
  birth: 1995/12/25
  age: 25
  interests:
    - 篮球
    - 足球
    - 排球
  animal: [阿猫,阿狗]
#  score:
#    english: 80
#    math: 90
  score: {english: 80,math: 90}
  salary:
    - 9999.98
    - 9999.99
  pet:
    name: 佩奇
    weight: 90.23
  allpets:
    sick:
      - {name: 阿狗,weight: 23.56}
      - name: 阿猫
        weight: 88.5
      - name: 爱宠
        weight: 56.2
    health:
      - {name: 阿狗1,weight: 23.561}
  user-name: 张三



#spring:
#  banner:
#    image:
#      bitdepth: 4
#  cache:
#    type: redis
#    redis:
#      time-to-live: 11000
